name: Tests

on: [push, pull_request]

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install JUCE dependencies
      run: |
        sudo apt-get update
        sudo apt install libasound2-dev libjack-jackd2-dev \
            ladspa-sdk \
            libcurl4-openssl-dev  \
            libfreetype-dev libfontconfig1-dev \
            libx11-dev libxcomposite-dev libxcursor-dev libxext-dev libxinerama-dev libxrandr-dev libxrender-dev \
            libwebkit2gtk-4.1-dev \
            libglu1-mesa-dev mesa-common-dev

    - name: Download JUCE
      run: |
        git clone --depth 1 --branch 8.0.6 https://github.com/juce-framework/JUCE.git ~/JUCE

    - name: Build and Run Tests
      run: |
        cd TestApplication/Builds/LinuxMakefile
        make CONFIG=Debug
        ./build/TestApplication